### ISSUE TITLE
Additional working mode: "exit" strategy

### ISSUE THREAD

**Issue by alecrt** [chefomar/angular-scroll-spy#11]
Hi @chefomar,

nice library. Works very well!
Is it possible to add and addtional mode which listen for elements _**exiting**_ from the screen?

Thank you,

**Comment by alecrt** [comment]
Let me better explain: I need to cosider an element "active" when the top of the element is outside the viewport and the bottom of the elment is still inside the viewport.

**Comment by chefomar** [comment]
Hi @alecrt. Thanks for your comment.

Currently there is no mode for watching exiting elements.

> Let me better explain: I need to cosider an element "active" when the top of the element is outside the viewport and the bottom of the elment is still inside the viewport.

If you know all the ids of the spied on elements, you can subscribe to `activeSpyTarget` from `ScrollSpyService`. This will give you the single active element in the viewport. You can then filter to find the inactive elements. Beware though that inactive does not mean the element is not in the viewport. The `activeSpyTarget` will give you the **last** element inside the viewport. Meaning, if there are 3 elements inside the viewport only the last is considered "active".

I am currently not actively maintaining this library. I welcome any helpful pull request though.
