### ISSUE TITLE
Update to Angular 10

### ISSUE THREAD

**Issue by JackDMF** [chefomar/angular-scroll-spy#12]
Hi just wanted to say thank you for your package!
And ask, whether you have any plans to update it to Angular 10 :-)

**Comment by chefomar** [comment]
Hi Jack

Thanks for your comments.

I may be able to release an update during next week.

**Comment by chefomar** [comment]
I just published a new version. Install the latest version (3.0.0) for Angular 10 support.

Closing this, if there are any further issues please let me know 😊

**Comment by JackDMF** [comment]
Thanks a lot :-)
