### ISSUE TITLE
Update for Angular 12?

### ISSUE THREAD

**Issue by JackDMF** [chefomar/angular-scroll-spy#14]
Hi again - it's just been a year since the last update to Angular 10... do you plan to update to Angular 12?

**Comment by wlievens** [comment]
Also interested here!

**Comment by chefomar** [comment]
Hi All,

I'm not actively maintaining the package currently. I wouldn't mind if someone created a pull request though.

**Comment by chefomar** [comment]
Hi all,

Package version 4.0.2 is now published thanks to #15 . Let me know if you face issues.
